### ISSUE TITLE
The type or namespace "AppTrackingTransparency" could not be found. On TVOS 

### ISSUE THREAD

**Issue by DreamShake133402** [lupidan/unity-apptrackingtransparency#4]
I have installed the package and when i try to use the AppTrackingTransparency in my code, it says it cannot be found. This is on TVOS platform. Does this package work for TVOS? using Unity Editor version 2019.4.29f1.

**Comment by lupidan** [comment]
It should work for tvOS too.
Namespace should be available in all platforms. If you can't find the namespace you are probably missing an assembly reference.
